services:
  gameserver:
    image: ghcr.io/roboruckus/roboruckus-game-server:main
    container_name: roboruckus
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ARGS= # Set launch arguments here, e.g. --options=botless
    volumes:
      - ./Ruckus/GameConfig:/app/GameConfig/
      - ./Ruckus/Images:/app/wwwroot/images/boards
    ports:
      - 8082:8082
    restart: unless-stopped # Set the server to auto-start and auto-restart