version: '3.2'

services:

  gameserver:
    image: roboruckus/game-server:latest
    container_name: roboruckus
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/Ruckus/Boards:/app/GameConfig/Boards
      - ~/Ruckus/Images:/app/wwwroot/images/boards
    ports:
      - 8082:8082

    #deploy:
    #  mode: global
    #  placement:
    #    constraints: [node.platform.os == linux]
